"""initial tables

Revision ID: 0def602a233c
Revises: 
Create Date: 2026-08-18 14:05:48.183130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0def602a233c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uniqe_chat_topic_id', 'topics', ['chat_id', 'topic_id'], unique=True)
    op.create_table('user_chats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('tg_file_id', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_topic_file', 'files', ['topic_id', 'tg_file_id'], unique=True)
    op.create_table('positions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_index('unique_topic_file', table_name='files')
    op.drop_table('files')
    op.drop_table('user_chats')
    op.drop_index('uniqe_chat_topic_id', table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
