"""replace file id with message id

Revision ID: d1a9f05da145
Revises: 0def602a233c
Create Date: 2026-08-21 09:20:37.376775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a9f05da145'
down_revision: Union[str, Sequence[str], None] = '0def602a233c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE files RESTART IDENTITY CASCADE")

    op.add_column('files', sa.Column('tg_message_id', sa.BigInteger(), nullable=False))
    op.drop_index(op.f('unique_topic_file'), table_name='files')
    op.create_index('unique_topic_file', 'files', ['topic_id', 'tg_message_id'], unique=True)
    op.drop_column('files', 'tg_file_id')
    op.drop_index(op.f('uniqe_chat_topic_id'), table_name='topics')
    op.create_index('unique_chat_topic_id', 'topics', ['chat_id', 'topic_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_chat_topic_id', table_name='topics')
    op.create_index(op.f('uniqe_chat_topic_id'), 'topics', ['chat_id', 'topic_id'], unique=True)
    op.add_column('files', sa.Column('tg_file_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index('unique_topic_file', table_name='files')
    op.create_index(op.f('unique_topic_file'), 'files', ['topic_id', 'tg_file_id'], unique=True)
    op.drop_column('files', 'tg_message_id')
    # ### end Alembic commands ###
